1.ndarray的特性
多维度

In [1]:
import numpy as np

In [ ]:
arr = np.array(1)#0维数组
print(arr)
print('arr的维度:',arr.ndim)

1
arr的维度: 0


In [3]:
arr = np.array([1,2,3])#1维数组
print(arr)
print('arr的维度:',arr.ndim)

[1 2 3]
arr的维度: 1


In [4]:
arr = np.array([[1,2,3],[4,5,6]])#2维数组
print(arr)
print('arr的维度:',arr.ndim)

[[1 2 3]
 [4 5 6]]
arr的维度: 2


同质性

In [5]:
arr = np.array([1,'hello'])#1维数组，元素类型为字符串
print(arr)

['1' 'hello']


In [6]:
arr = np.array([1,2.5])#1维数组，元素类型为浮点数
print(arr)

[1.  2.5]
