In [2]:
import numpy as np

In [3]:
#基础的创建方法
arr = [1,2,3]
arr = np.array(arr,dtype=np.float32)
print(arr.ndim) #维度
print(arr)

1
[1. 2. 3.]


In [4]:
#copy方法创建
arr2 = arr.copy()#深拷贝
print(arr2)

[1. 2. 3.]


In [6]:
#预定义数组
arr = np.zeros((2,3)) #创建一个包含6个零的数组
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
#全一
arr = np.ones((2,3),dtype=np.int32) #创建一个包含6个一的数组
print(arr)

[[1 1 1]
 [1 1 1]]


In [10]:
#未初始化
arr = np.empty((2,3)) #创建一个包含6个未初始化的数组
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr = np.empty([3,5])#创建一个包含15个未初始化的数组
print(arr)

[[1.41897854e-311 3.35964639e-322 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [1.16095484e-028 2.17237198e-153 1.13224202e+277 9.21780235e+135
  1.07441485e+160]
 [1.46899930e+179 9.08367237e+223 1.16466228e-028 1.03775592e-314
  2.29178686e-312]]


In [13]:
#np.full
arr = np.full((2,3),5)#创建一个二维数组，元素全为5
print(arr)

[[5 5 5]
 [5 5 5]]


In [14]:
#np.zeros_like(arr)#返回arr的零矩阵
arr = np.zeros_like(arr)#创建一个和arr一样大小的零矩阵
print(arr)

[[0 0 0]
 [0 0 0]]
