In [1]:
import numpy as np

In [2]:
#特殊矩阵
#单位矩阵:主对角线上元素为1，其他元素为0的矩阵
arr = np.eye(5,dtype=np.int32) #创建一个5行5列的单位矩阵
print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [3]:
arr = np.eye(3,4,dtype=np.int32) #创建一个3行4列的单位矩阵
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [4]:
#对角矩阵:主对角线上元素为指定值，其他元素为0的矩阵
arr = np.diag([1,2,3,4]) #创建一个对角矩阵，参数为一个列表，列表中的元素为主对角线上的元素
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [7]:
#生成随机数组
#生成0~1之间的随机浮点数(均匀分布)
arr = np.random.rand(2,3) #创建一个2行3列的随机数组
print(arr)

[[0.18719973 0.65397205 0.64300429]
 [0.70219137 0.0513991  0.31143301]]


In [9]:
#生成指定范围内的随机浮点数
arr = np.random.uniform(3,4,5) #创建一个包含5个元素的随机数组，元素的值在0~1之间
print(arr)

[3.04867476 3.06221826 3.76500906 3.96863224 3.11817351]


In [10]:
##生成指定范围内的随机整数
arr = np.random.randint(0,10,5)
print(arr)

[5 9 5 4 4]


In [ ]:
#生成随机数列(正态分布) 
arr = np.random.randn(2,3)
print(arr)

[[ 1.24030158  1.15084966 -2.13093132]
 [-0.30538283 -1.26122584  0.40834389]]


In [15]:
#设置随机种子
np.random.seed(20) #设置随机种子为20
arr = np.random.randint(1,10,size=(2,5))
print(arr)
np.random.seed() #取消随机种子设置

[[4 5 7 8 3]
 [1 7 9 6 4]]
