In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,100,size=(2,5))
print(arr)

[[32 63 83 27 61]
 [99 68 52 95 28]]


In [11]:
print(arr[0][3]) #访问数组元素
print(arr[0])
print(arr[:])
print(arr[0][2:5])
print(arr[arr>50]) #访问满足条件的元素
print(arr[(arr>30) & (arr<70)]) #访问满足多个条件的元素

27
[32 63 83 27 61]
[[32 63 83 27 61]
 [99 68 52 95 28]]
[83 27 61]
[63 83 61 99 68 52 95]
[32 63 61 68 52]
