In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [3]:
c = [1, 2, 3]
d = [4, 5, 6]
print(c+d)

[1, 2, 3, 4, 5, 6]


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr+3)
print(arr*3)

[[4 5 6]
 [7 8 9]]
[[ 3  6  9]
 [12 15 18]]


In [7]:
#广播机制:从后往前看维度，要么相等，要么有一个是 1
a = np.array([1,2,3])#1*3
b = np.array([[4],[5],[6]])#3*1
print(a+b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [17]:
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([[4,5,6],[7,8,9]])
c = np.array([[4, 5],[7, 8],[10, 11]])
#对应的数相乘:a的元素个数要等于b的元素个数
print(a*b)
#矩阵相乘:a的行数要等于b的列数
print(a @ c)
print(a.dot(c))

[[ 4 10 18]
 [28 40 54]]
[[ 48  54]
 [111 126]]
[[ 48  54]
 [111 126]]
